app:
  time:
    fff: '{{ "%03d" % (leadtime.total_seconds() // 3600) }}'
    hh: '{{ cycle.strftime("%H") }}'
    m1_hh: '{{ (cycle - app.time.m6h).strftime("%H") }}'
    m1_yyyymmdd: '{{ (cycle - app.time.m6h).strftime("%Y%m%d") }}'
    m2_hh: '{{ (cycle - 2 * app.time.m6h).strftime("%H") }}'
    m2_yyyymmdd: '{{ (cycle - 2 * app.time.m6h).strftime("%Y%m%d") }}'
    m6h: !timedelta 6
    yyyymmdd: '{{ cycle.strftime("%Y%m%d") }}'
forecast:
  aigfs_inference:
    diffs_stddev_path: '{{ app.modeldir }}/stats/diffs_stddev_by_level.nc'
    execution:
      batchargs:
        debug: True
        memory: 150GB
        nodes: 1
        tasks_per_node: 128
        walltime: 00:20:00
      executable: null
    forecast_freq: 6
    forecast_length: 24
    grib_out_config: '{{ app.home }}/etc/grib-out.json'
    ics_path: '{{ prep.aigfs_ics.rundir }}/aigfs.t{{ app.time.hh }}z.ic.nc'
    mean_path: '{{ app.modeldir }}/stats/mean_by_level.nc'
    model_weights_path: '{{ app.modeldir }}/params/weights.npz'
    rundir: '{{ app.rundir }}/{{ app.time.yyyymmdd }}{{ app.time.hh }}/forecast'
    stddev_path: '{{ app.modeldir }}/stats/stddev_by_level.nc'
  platform:
    account: '{{ app.platform.scheduler.account }}'
    scheduler: '{{ app.platform.scheduler.type }}'
post:
  aigfs_post:
    execution:
      batchargs:
        cores: 1
        debug: True
        memory: 4GB
        walltime: 00:01:00
      executable: null
    deliver_to: '{{ forecast.aigfs_inference.rundir }}'
    inputfiles:
      - '{{ forecast.aigfs_inference.rundir }}/aigfs.t{{ app.time.hh }}z.sfc.f{{ app.time.fff }}.grib2'
      - '{{ forecast.aigfs_inference.rundir }}/aigfs.t{{ app.time.hh }}z.pres.f{{ app.time.fff }}.grib2'
    outputdir: '{{ post.aigfs_post.rundir }}'
    rundir: '{{ app.rundir }}/{{ app.time.yyyymmdd }}{{ app.time.hh }}/post_{{ app.time.fff }}'
  platform:
    account: '{{ app.platform.scheduler.account }}'
    scheduler: '{{ app.platform.scheduler.type }}'
prep:
  aigfs_ics:
    execution:
      batchargs:
        cores: 1
        debug: True
        memory: 10GB
        walltime: 00:05:00
      executable: null
    grib_in_config: '{{ app.home }}/etc/grib-in.yaml'
    rundir: '{{ app.rundir }}/{{ app.time.yyyymmdd }}{{ app.time.hh }}/prep'
  platform:
    account: '{{ app.platform.scheduler.account }}'
    scheduler: '{{ app.platform.scheduler.type }}'
